/** @generated by @calimero/abi-codegen — DO NOT EDIT. */

import type { MeroJs } from '@calimero-network/mero-js';

// Generated types

export type AbiEvent =
  | { name: 'Inserted' }
  | { name: 'Updated' }
  | { name: 'Removed' }
  | { name: 'Cleared' };

/**
 * Context information for RPC calls
 */
export interface AppContext {
  contextId: string;
  executorPublicKey: string;
  applicationId: string;
}

/**
 * Utility class for handling byte conversions in Calimero
 */
export class CalimeroBytes {
  private data: Uint8Array;

  constructor(input: string | number[] | Uint8Array) {
    if (typeof input === 'string') {
      // Hex string
      this.data = new Uint8Array(
        input.match(/.{1,2}/g)?.map((byte) => parseInt(byte, 16)) || [],
      );
    } else if (Array.isArray(input)) {
      // Number array
      this.data = new Uint8Array(input);
    } else {
      // Uint8Array
      this.data = input;
    }
  }

  toArray(): number[] {
    return Array.from(this.data);
  }

  toUint8Array(): Uint8Array {
    return this.data;
  }

  static fromHex(hex: string): CalimeroBytes {
    return new CalimeroBytes(hex);
  }

  static fromArray(arr: number[]): CalimeroBytes {
    return new CalimeroBytes(arr);
  }

  static fromUint8Array(bytes: Uint8Array): CalimeroBytes {
    return new CalimeroBytes(bytes);
  }
}

export class AbiClient {
  private mero: MeroJs;
  private context: AppContext;

  constructor(mero: MeroJs, context: AppContext) {
    this.mero = mero;
    this.context = context;
  }

  /**
   * Execute an RPC method
   */
  private async execute<T>(method: string, args: Record<string, unknown> = {}): Promise<T> {
    const result = await this.mero.rpc.execute({
      contextId: this.context.contextId,
      method,
      args,
      executorPublicKey: this.context.executorPublicKey,
    });
    return result.output as T;
  }

  /**
   * init
   */
  public async init(): Promise<void> {
    await this.execute<void>('init');
  }

  /**
   * set
   */
  public async set(params: { key: string; value: string }): Promise<void> {
    await this.execute<void>('set', params);
  }

  /**
   * entries
   */
  public async entries(): Promise<Record<string, string>> {
    return this.execute<Record<string, string>>('entries');
  }

  /**
   * len
   */
  public async len(): Promise<number> {
    return this.execute<number>('len');
  }

  /**
   * get
   */
  public async get(params: { key: string }): Promise<string> {
    return this.execute<string>('get', params);
  }

  /**
   * get_unchecked
   */
  public async getUnchecked(params: { key: string }): Promise<string> {
    return this.execute<string>('get_unchecked', params);
  }

  /**
   * get_result
   */
  public async getResult(params: { key: string }): Promise<string> {
    return this.execute<string>('get_result', params);
  }

  /**
   * remove
   */
  public async remove(params: { key: string }): Promise<string> {
    return this.execute<string>('remove', params);
  }

  /**
   * clear
   */
  public async clear(): Promise<void> {
    await this.execute<void>('clear');
  }
}
